leaf:
  name: fspm.models.organs.Leaf
  subbed-updates:
    - fspm.functions.Growth
    - fspm.functions.LightInterception
  self-functions:
    - fspm.functions.LeafShape
  update-functions:
    - fspm.functions.LeafGrowth # required for Growth update

fruit:
  name: fspm.models.organs.Fruit
  subbed-updates:
    - fspm.functions.Growth
  update-functions:
    - fspm.functions.FruitGrowth